pipeline {
    agent any
    
    environment {
     AWS_ACCESS_KEY_ID     = credentials('access-key')
     AWS_SECRET_ACCESS_KEY = credentials('secrete-key')
    }
    
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        
        
       stage('Git CheckOut') {
           steps {
                 git branch: 'main', url: 'https://github.com/dhananjaypatil80/Terraform.git'
           }
               
        }  
        
        stage('terraform init') {
           steps {
               
               
                 sh ('terraform init ')
           }
        }
        
        
        
        
         stage('terraform fmt') {
           steps {
                 
                 sh ('terraform fmt ')
           }
        }
        
        
        stage('terraform plan') {
           steps {
                 
                 sh ('terraform plan ')
           }
        }
        
        
        
        stage('terraform apply -auto-approve') {
           steps {
                  
                 sh ('terraform apply -auto-approve')
           }
        }
        
        
     
        
    }
    
}


































































                
          
